name: Plot Github Action
on:
  push:
    branches:
      - main  

 

jobs:
  analyze_data:
    runs-on: ubuntu-latest

 

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

 

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

 

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl
        pip install matplotlib
        pip install seaborn
        pip install -U scikit-learn

 

    - name: Run Analysis
      run: python Girishassignment-3.6/main.py 
    - name: Save Plots as Artifacts
      uses: actions/upload-artifact@v2
      with:
          name: plots
          path: 
           Girishassignment-3.6/plot_test_size_0_2.png
           Girishassignment-3.6/plot_test_size_0_3.png
           Girishassignment-3.6/plot_test_size_0_4.png
 

  
